query GetAccountCollections {
	accountCollections(orderBy: tokenCount, orderDirection: desc, first: 5) {
		account {
			id
			tokens(first: 1) {
				collection {
					name
					symbol
					totalVolume
				}
			}
		}
		tokenCount
	}
}
